services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=schnipseldb'
      - 'POSTGRES_PASSWORD=schnipselpassword'
      - 'POSTGRES_USER=schnipseluser'
    ports:
      - '5432:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    command: start-dev
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
      - 'KC_HTTP_PORT=8090'
    ports:
      - '8090:8090'
