spring:
  config:
    import: optional:file:.env.properties
  application:
    name: Schnipsel
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: trace

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: schnipsel
#            client-name: schnipsel
#            client-secret: PB62FiIdDvCIM4hgqoSdvy7uv7p7FXQG
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email
#            redirect-uri: http://localhost:8080/login/oauth2/code/schnipsel
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8090/realms/master
#            authorization-uri: http://localhost:8090/realms/master/protocol/openid-connect/auth

